export const ALL_ROUTES = [
  {
    id: 'OPT-001',
    company: 'Amazon',
    city: 'New Delhi',
    state: 'Delhi',
    driver: 'Rajan Kumar',
    driverInitials: 'RK',
    vehicleId: 'DL-4521',
    origin: 'Sector 14 Dwarka',
    destination: 'Connaught Place',
    stops: 8,
    manualDistance: 48,
    manualFuelCost: 820,
    manualTime: '2h 40m',
    manualTimeMinutes: 160,
    optimizedDistance: 31,
    optimizedFuelCost: 530,
    optimizedTime: '1h 45m',
    optimizedTimeMinutes: 105,
    distanceSaved: 17,
    fuelSaved: 290,
    timeSaved: 55,
    distanceReduction: 35,
    status: 'Active',
    optimizedAt: '10:24 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 14,
    confidence: 94,
    routeStops: [
      { name: 'Sector 14 Dwarka', type: 'origin', sequence: 1 },
      { name: 'Rajouri Garden', type: 'stop', sequence: 2 },
      { name: 'Patel Nagar', type: 'stop', sequence: 3 },
      { name: 'Karol Bagh', type: 'stop', sequence: 4 },
      { name: 'Paharganj', type: 'stop', sequence: 5 },
      { name: 'Connaught Place', type: 'destination', sequence: 6 },
    ],
    manualStops: [
      { name: 'Connaught Place', sequence: 1 },
      { name: 'Paharganj', sequence: 2 },
      { name: 'Sector 14 Dwarka', sequence: 3 },
      { name: 'Karol Bagh', sequence: 4 },
      { name: 'Patel Nagar', sequence: 5 },
      { name: 'Rajouri Garden', sequence: 6 },
    ],
  },
  {
    id: 'OPT-002',
    company: 'Amazon',
    city: 'New Delhi',
    state: 'Delhi',
    driver: 'Suresh Verma',
    driverInitials: 'SV',
    vehicleId: 'DL-7823',
    origin: 'Noida Sector 62',
    destination: 'Lajpat Nagar',
    stops: 10,
    manualDistance: 55,
    manualFuelCost: 940,
    manualTime: '3h 10m',
    manualTimeMinutes: 190,
    optimizedDistance: 38,
    optimizedFuelCost: 648,
    optimizedTime: '2h 12m',
    optimizedTimeMinutes: 132,
    distanceSaved: 17,
    fuelSaved: 292,
    timeSaved: 58,
    distanceReduction: 31,
    status: 'Active',
    optimizedAt: '09:15 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 14,
    confidence: 91,
    routeStops: [
      { name: 'Noida Sector 62', type: 'origin', sequence: 1 },
      { name: 'Noida Sector 18', type: 'stop', sequence: 2 },
      { name: 'Mayur Vihar', type: 'stop', sequence: 3 },
      { name: 'Akshardham', type: 'stop', sequence: 4 },
      { name: 'Pragati Maidan', type: 'stop', sequence: 5 },
      { name: 'Lajpat Nagar', type: 'destination', sequence: 6 },
    ],
    manualStops: [
      { name: 'Lajpat Nagar', sequence: 1 },
      { name: 'Akshardham', sequence: 2 },
      { name: 'Noida Sector 62', sequence: 3 },
      { name: 'Pragati Maidan', sequence: 4 },
      { name: 'Noida Sector 18', sequence: 5 },
      { name: 'Mayur Vihar', sequence: 6 },
    ],
  },
  {
    id: 'OPT-003',
    company: 'Amazon',
    city: 'Gurugram',
    state: 'Delhi',
    driver: 'Amit Sharma',
    driverInitials: 'AS',
    vehicleId: 'HR-0192',
    origin: 'DLF Phase 1',
    destination: 'Cyber City',
    stops: 7,
    manualDistance: 42,
    manualFuelCost: 715,
    manualTime: '2h 20m',
    manualTimeMinutes: 140,
    optimizedDistance: 29,
    optimizedFuelCost: 494,
    optimizedTime: '1h 38m',
    optimizedTimeMinutes: 98,
    distanceSaved: 13,
    fuelSaved: 221,
    timeSaved: 42,
    distanceReduction: 31,
    status: 'Completed',
    optimizedAt: '08:00 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 12,
    confidence: 88,
    routeStops: [
      { name: 'DLF Phase 1', type: 'origin', sequence: 1 },
      { name: 'Sikanderpur', type: 'stop', sequence: 2 },
      { name: 'MG Road', type: 'stop', sequence: 3 },
      { name: 'IFFCO Chowk', type: 'stop', sequence: 4 },
      { name: 'Cyber City', type: 'destination', sequence: 5 },
    ],
    manualStops: [
      { name: 'Cyber City', sequence: 1 },
      { name: 'DLF Phase 1', sequence: 2 },
      { name: 'IFFCO Chowk', sequence: 3 },
      { name: 'Sikanderpur', sequence: 4 },
      { name: 'MG Road', sequence: 5 },
    ],
  },
  {
    id: 'OPT-004',
    company: 'Amazon',
    city: 'Mumbai',
    state: 'Maharashtra',
    driver: 'Pradeep Patil',
    driverInitials: 'PP',
    vehicleId: 'MH-1234',
    origin: 'Andheri East',
    destination: 'Bandra Kurla Complex',
    stops: 9,
    manualDistance: 52,
    manualFuelCost: 885,
    manualTime: '2h 55m',
    manualTimeMinutes: 175,
    optimizedDistance: 35,
    optimizedFuelCost: 595,
    optimizedTime: '1h 58m',
    optimizedTimeMinutes: 118,
    distanceSaved: 17,
    fuelSaved: 290,
    timeSaved: 57,
    distanceReduction: 33,
    status: 'Active',
    optimizedAt: '10:45 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 16,
    confidence: 92,
    routeStops: [
      { name: 'Andheri East', type: 'origin', sequence: 1 },
      { name: 'Kurla West', type: 'stop', sequence: 2 },
      { name: 'Kalina', type: 'stop', sequence: 3 },
      { name: 'Santacruz East', type: 'stop', sequence: 4 },
      { name: 'Bandra Kurla Complex', type: 'destination', sequence: 5 },
    ],
    manualStops: [
      { name: 'Santacruz East', sequence: 1 },
      { name: 'Bandra Kurla Complex', sequence: 2 },
      { name: 'Andheri East', sequence: 3 },
      { name: 'Kalina', sequence: 4 },
      { name: 'Kurla West', sequence: 5 },
    ],
  },
  {
    id: 'OPT-005',
    company: 'Amazon',
    city: 'Pune',
    state: 'Maharashtra',
    driver: 'Vishal Deshmukh',
    driverInitials: 'VD',
    vehicleId: 'MH-4456',
    origin: 'Kothrud',
    destination: 'Hadapsar',
    stops: 6,
    manualDistance: 38,
    manualFuelCost: 648,
    manualTime: '2h 05m',
    manualTimeMinutes: 125,
    optimizedDistance: 27,
    optimizedFuelCost: 460,
    optimizedTime: '1h 30m',
    optimizedTimeMinutes: 90,
    distanceSaved: 11,
    fuelSaved: 188,
    timeSaved: 35,
    distanceReduction: 29,
    status: 'Pending',
    optimizedAt: '11:02 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 11,
    confidence: 86,
    routeStops: [
      { name: 'Kothrud', type: 'origin', sequence: 1 },
      { name: 'Karve Nagar', type: 'stop', sequence: 2 },
      { name: 'Swargate', type: 'stop', sequence: 3 },
      { name: 'Wanowrie', type: 'stop', sequence: 4 },
      { name: 'Hadapsar', type: 'destination', sequence: 5 },
    ],
    manualStops: [
      { name: 'Hadapsar', sequence: 1 },
      { name: 'Kothrud', sequence: 2 },
      { name: 'Wanowrie', sequence: 3 },
      { name: 'Karve Nagar', sequence: 4 },
      { name: 'Swargate', sequence: 5 },
    ],
  },
  {
    id: 'OPT-006',
    company: 'Flipkart',
    city: 'Bengaluru',
    state: 'Karnataka',
    driver: 'Kiran Murthy',
    driverInitials: 'KM',
    vehicleId: 'KA-0921',
    origin: 'Whitefield',
    destination: 'Koramangala',
    stops: 11,
    manualDistance: 61,
    manualFuelCost: 1038,
    manualTime: '3h 25m',
    manualTimeMinutes: 205,
    optimizedDistance: 41,
    optimizedFuelCost: 698,
    optimizedTime: '2h 18m',
    optimizedTimeMinutes: 138,
    distanceSaved: 20,
    fuelSaved: 340,
    timeSaved: 67,
    distanceReduction: 33,
    status: 'Active',
    optimizedAt: '09:55 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 17,
    confidence: 96,
    routeStops: [
      { name: 'Whitefield', type: 'origin', sequence: 1 },
      { name: 'Marathahalli', type: 'stop', sequence: 2 },
      { name: 'Bellandur', type: 'stop', sequence: 3 },
      { name: 'HSR Layout', type: 'stop', sequence: 4 },
      { name: 'BTM Layout', type: 'stop', sequence: 5 },
      { name: 'Koramangala', type: 'destination', sequence: 6 },
    ],
    manualStops: [
      { name: 'BTM Layout', sequence: 1 },
      { name: 'Whitefield', sequence: 2 },
      { name: 'Koramangala', sequence: 3 },
      { name: 'Bellandur', sequence: 4 },
      { name: 'Marathahalli', sequence: 5 },
      { name: 'HSR Layout', sequence: 6 },
    ],
  },
  {
    id: 'OPT-007',
    company: 'Flipkart',
    city: 'Bengaluru',
    state: 'Karnataka',
    driver: 'Naveen Raj',
    driverInitials: 'NR',
    vehicleId: 'KA-5543',
    origin: 'Electronic City',
    destination: 'Indiranagar',
    stops: 9,
    manualDistance: 57,
    manualFuelCost: 970,
    manualTime: '3h 10m',
    manualTimeMinutes: 190,
    optimizedDistance: 38,
    optimizedFuelCost: 646,
    optimizedTime: '2h 08m',
    optimizedTimeMinutes: 128,
    distanceSaved: 19,
    fuelSaved: 324,
    timeSaved: 62,
    distanceReduction: 33,
    status: 'Active',
    optimizedAt: '10:10 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 15,
    confidence: 93,
    routeStops: [
      { name: 'Electronic City', type: 'origin', sequence: 1 },
      { name: 'Bommanahalli', type: 'stop', sequence: 2 },
      { name: 'HSR Layout', type: 'stop', sequence: 3 },
      { name: 'Koramangala', type: 'stop', sequence: 4 },
      { name: 'Domlur', type: 'stop', sequence: 5 },
      { name: 'Indiranagar', type: 'destination', sequence: 6 },
    ],
    manualStops: [
      { name: 'Indiranagar', sequence: 1 },
      { name: 'Electronic City', sequence: 2 },
      { name: 'Domlur', sequence: 3 },
      { name: 'Bommanahalli', sequence: 4 },
      { name: 'Koramangala', sequence: 5 },
      { name: 'HSR Layout', sequence: 6 },
    ],
  },
  {
    id: 'OPT-008',
    company: 'Flipkart',
    city: 'Mumbai',
    state: 'Maharashtra',
    driver: 'Santosh Naik',
    driverInitials: 'SN',
    vehicleId: 'MH-8871',
    origin: 'Thane West',
    destination: 'Powai',
    stops: 8,
    manualDistance: 46,
    manualFuelCost: 783,
    manualTime: '2h 35m',
    manualTimeMinutes: 155,
    optimizedDistance: 32,
    optimizedFuelCost: 545,
    optimizedTime: '1h 48m',
    optimizedTimeMinutes: 108,
    distanceSaved: 14,
    fuelSaved: 238,
    timeSaved: 47,
    distanceReduction: 30,
    status: 'Completed',
    optimizedAt: '07:30 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 13,
    confidence: 89,
    routeStops: [
      { name: 'Thane West', type: 'origin', sequence: 1 },
      { name: 'Ghodbunder Road', type: 'stop', sequence: 2 },
      { name: 'Mulund West', type: 'stop', sequence: 3 },
      { name: 'Vikhroli', type: 'stop', sequence: 4 },
      { name: 'Powai', type: 'destination', sequence: 5 },
    ],
    manualStops: [
      { name: 'Powai', sequence: 1 },
      { name: 'Thane West', sequence: 2 },
      { name: 'Vikhroli', sequence: 3 },
      { name: 'Ghodbunder Road', sequence: 4 },
      { name: 'Mulund West', sequence: 5 },
    ],
  },
  {
    id: 'OPT-009',
    company: 'Flipkart',
    city: 'Ludhiana',
    state: 'Punjab',
    driver: 'Gurpreet Singh',
    driverInitials: 'GS',
    vehicleId: 'PB-1144',
    origin: 'Model Town',
    destination: 'Sarabha Nagar',
    stops: 7,
    manualDistance: 39,
    manualFuelCost: 664,
    manualTime: '2h 10m',
    manualTimeMinutes: 130,
    optimizedDistance: 27,
    optimizedFuelCost: 459,
    optimizedTime: '1h 31m',
    optimizedTimeMinutes: 91,
    distanceSaved: 12,
    fuelSaved: 205,
    timeSaved: 39,
    distanceReduction: 31,
    status: 'Active',
    optimizedAt: '10:00 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 12,
    confidence: 90,
    routeStops: [
      { name: 'Model Town', type: 'origin', sequence: 1 },
      { name: 'Civil Lines', type: 'stop', sequence: 2 },
      { name: 'Dugri', type: 'stop', sequence: 3 },
      { name: 'BRS Nagar', type: 'stop', sequence: 4 },
      { name: 'Sarabha Nagar', type: 'destination', sequence: 5 },
    ],
    manualStops: [
      { name: 'Sarabha Nagar', sequence: 1 },
      { name: 'Model Town', sequence: 2 },
      { name: 'BRS Nagar', sequence: 3 },
      { name: 'Civil Lines', sequence: 4 },
      { name: 'Dugri', sequence: 5 },
    ],
  },
  {
    id: 'OPT-010',
    company: 'Meesho',
    city: 'Chennai',
    state: 'Tamil Nadu',
    driver: 'Murugan Selvam',
    driverInitials: 'MS',
    vehicleId: 'TN-3322',
    origin: 'Tambaram',
    destination: 'Anna Nagar',
    stops: 10,
    manualDistance: 58,
    manualFuelCost: 987,
    manualTime: '3h 15m',
    manualTimeMinutes: 195,
    optimizedDistance: 40,
    optimizedFuelCost: 680,
    optimizedTime: '2h 15m',
    optimizedTimeMinutes: 135,
    distanceSaved: 18,
    fuelSaved: 307,
    timeSaved: 60,
    distanceReduction: 31,
    status: 'Active',
    optimizedAt: '09:45 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 14,
    confidence: 91,
    routeStops: [
      { name: 'Tambaram', type: 'origin', sequence: 1 },
      { name: 'Chromepet', type: 'stop', sequence: 2 },
      { name: 'Guindy', type: 'stop', sequence: 3 },
      { name: 'T Nagar', type: 'stop', sequence: 4 },
      { name: 'Vadapalani', type: 'stop', sequence: 5 },
      { name: 'Anna Nagar', type: 'destination', sequence: 6 },
    ],
    manualStops: [
      { name: 'Anna Nagar', sequence: 1 },
      { name: 'Tambaram', sequence: 2 },
      { name: 'Vadapalani', sequence: 3 },
      { name: 'Guindy', sequence: 4 },
      { name: 'T Nagar', sequence: 5 },
      { name: 'Chromepet', sequence: 6 },
    ],
  },
  {
    id: 'OPT-011',
    company: 'Meesho',
    city: 'Chennai',
    state: 'Tamil Nadu',
    driver: 'Arun Krishnan',
    driverInitials: 'AK',
    vehicleId: 'TN-5511',
    origin: 'Velachery',
    destination: 'Porur',
    stops: 8,
    manualDistance: 44,
    manualFuelCost: 749,
    manualTime: '2h 28m',
    manualTimeMinutes: 148,
    optimizedDistance: 30,
    optimizedFuelCost: 511,
    optimizedTime: '1h 42m',
    optimizedTimeMinutes: 102,
    distanceSaved: 14,
    fuelSaved: 238,
    timeSaved: 46,
    distanceReduction: 32,
    status: 'Completed',
    optimizedAt: '08:20 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 13,
    confidence: 87,
    routeStops: [
      { name: 'Velachery', type: 'origin', sequence: 1 },
      { name: 'Medavakkam', type: 'stop', sequence: 2 },
      { name: 'Pallikaranai', type: 'stop', sequence: 3 },
      { name: 'Sholinganallur', type: 'stop', sequence: 4 },
      { name: 'Porur', type: 'destination', sequence: 5 },
    ],
    manualStops: [
      { name: 'Porur', sequence: 1 },
      { name: 'Velachery', sequence: 2 },
      { name: 'Sholinganallur', sequence: 3 },
      { name: 'Pallikaranai', sequence: 4 },
      { name: 'Medavakkam', sequence: 5 },
    ],
  },
  {
    id: 'OPT-012',
    company: 'Meesho',
    city: 'Pune',
    state: 'Maharashtra',
    driver: 'Rohit Jadhav',
    driverInitials: 'RJ',
    vehicleId: 'MH-9903',
    origin: 'Wakad',
    destination: 'Viman Nagar',
    stops: 9,
    manualDistance: 50,
    manualFuelCost: 851,
    manualTime: '2h 48m',
    manualTimeMinutes: 168,
    optimizedDistance: 34,
    optimizedFuelCost: 579,
    optimizedTime: '1h 54m',
    optimizedTimeMinutes: 114,
    distanceSaved: 16,
    fuelSaved: 272,
    timeSaved: 54,
    distanceReduction: 32,
    status: 'Active',
    optimizedAt: '10:33 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 15,
    confidence: 93,
    routeStops: [
      { name: 'Wakad', type: 'origin', sequence: 1 },
      { name: 'Pimpri', type: 'stop', sequence: 2 },
      { name: 'Chinchwad', type: 'stop', sequence: 3 },
      { name: 'Aundh', type: 'stop', sequence: 4 },
      { name: 'Kharadi', type: 'stop', sequence: 5 },
      { name: 'Viman Nagar', type: 'destination', sequence: 6 },
    ],
    manualStops: [
      { name: 'Viman Nagar', sequence: 1 },
      { name: 'Wakad', sequence: 2 },
      { name: 'Kharadi', sequence: 3 },
      { name: 'Pimpri', sequence: 4 },
      { name: 'Aundh', sequence: 5 },
      { name: 'Chinchwad', sequence: 6 },
    ],
  },
  {
    id: 'OPT-013',
    company: 'Meesho',
    city: 'Amritsar',
    state: 'Punjab',
    driver: 'Harjinder Kaur',
    driverInitials: 'HK',
    vehicleId: 'PB-6612',
    origin: 'Lawrence Road',
    destination: 'Ranjit Avenue',
    stops: 6,
    manualDistance: 35,
    manualFuelCost: 596,
    manualTime: '1h 58m',
    manualTimeMinutes: 118,
    optimizedDistance: 24,
    optimizedFuelCost: 409,
    optimizedTime: '1h 22m',
    optimizedTimeMinutes: 82,
    distanceSaved: 11,
    fuelSaved: 187,
    timeSaved: 36,
    distanceReduction: 31,
    status: 'Active',
    optimizedAt: '09:30 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 11,
    confidence: 88,
    routeStops: [
      { name: 'Lawrence Road', type: 'origin', sequence: 1 },
      { name: 'Majitha Road', type: 'stop', sequence: 2 },
      { name: 'GT Road', type: 'stop', sequence: 3 },
      { name: 'Sultanwind', type: 'stop', sequence: 4 },
      { name: 'Ranjit Avenue', type: 'destination', sequence: 5 },
    ],
    manualStops: [
      { name: 'Ranjit Avenue', sequence: 1 },
      { name: 'Lawrence Road', sequence: 2 },
      { name: 'Sultanwind', sequence: 3 },
      { name: 'Majitha Road', sequence: 4 },
      { name: 'GT Road', sequence: 5 },
    ],
  },
  {
    id: 'OPT-014',
    company: 'Zomato',
    city: 'New Delhi',
    state: 'Delhi',
    driver: 'Deepak Yadav',
    driverInitials: 'DY',
    vehicleId: 'DL-2234',
    origin: 'Rohini Sector 7',
    destination: 'Pitampura',
    stops: 12,
    manualDistance: 64,
    manualFuelCost: 1088,
    manualTime: '3h 35m',
    manualTimeMinutes: 215,
    optimizedDistance: 43,
    optimizedFuelCost: 731,
    optimizedTime: '2h 24m',
    optimizedTimeMinutes: 144,
    distanceSaved: 21,
    fuelSaved: 357,
    timeSaved: 71,
    distanceReduction: 33,
    status: 'Active',
    optimizedAt: '11:15 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 18,
    confidence: 95,
    routeStops: [
      { name: 'Rohini Sector 7', type: 'origin', sequence: 1 },
      { name: 'Rohini Sector 11', type: 'stop', sequence: 2 },
      { name: 'Prashant Vihar', type: 'stop', sequence: 3 },
      { name: 'Kohat Enclave', type: 'stop', sequence: 4 },
      { name: 'Shalimar Bagh', type: 'stop', sequence: 5 },
      { name: 'Pitampura', type: 'destination', sequence: 6 },
    ],
    manualStops: [
      { name: 'Pitampura', sequence: 1 },
      { name: 'Rohini Sector 7', sequence: 2 },
      { name: 'Shalimar Bagh', sequence: 3 },
      { name: 'Rohini Sector 11', sequence: 4 },
      { name: 'Kohat Enclave', sequence: 5 },
      { name: 'Prashant Vihar', sequence: 6 },
    ],
  },
  {
    id: 'OPT-015',
    company: 'Zomato',
    city: 'Mumbai',
    state: 'Maharashtra',
    driver: 'Akash Gaikwad',
    driverInitials: 'AG',
    vehicleId: 'MH-5567',
    origin: 'Goregaon West',
    destination: 'Malad East',
    stops: 7,
    manualDistance: 40,
    manualFuelCost: 680,
    manualTime: '2h 14m',
    manualTimeMinutes: 134,
    optimizedDistance: 27,
    optimizedFuelCost: 460,
    optimizedTime: '1h 31m',
    optimizedTimeMinutes: 91,
    distanceSaved: 13,
    fuelSaved: 220,
    timeSaved: 43,
    distanceReduction: 33,
    status: 'Completed',
    optimizedAt: '07:45 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 13,
    confidence: 90,
    routeStops: [
      { name: 'Goregaon West', type: 'origin', sequence: 1 },
      { name: 'Oshiwara', type: 'stop', sequence: 2 },
      { name: 'Lokhandwala', type: 'stop', sequence: 3 },
      { name: 'Infinity Mall', type: 'stop', sequence: 4 },
      { name: 'Malad East', type: 'destination', sequence: 5 },
    ],
    manualStops: [
      { name: 'Malad East', sequence: 1 },
      { name: 'Goregaon West', sequence: 2 },
      { name: 'Infinity Mall', sequence: 3 },
      { name: 'Lokhandwala', sequence: 4 },
      { name: 'Oshiwara', sequence: 5 },
    ],
  },
  {
    id: 'OPT-016',
    company: 'Zomato',
    city: 'Bengaluru',
    state: 'Karnataka',
    driver: 'Ravi Shankar',
    driverInitials: 'RS',
    vehicleId: 'KA-3312',
    origin: 'Jayanagar',
    destination: 'JP Nagar',
    stops: 8,
    manualDistance: 45,
    manualFuelCost: 766,
    manualTime: '2h 32m',
    manualTimeMinutes: 152,
    optimizedDistance: 30,
    optimizedFuelCost: 511,
    optimizedTime: '1h 42m',
    optimizedTimeMinutes: 102,
    distanceSaved: 15,
    fuelSaved: 255,
    timeSaved: 50,
    distanceReduction: 33,
    status: 'Active',
    optimizedAt: '10:50 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 14,
    confidence: 92,
    routeStops: [
      { name: 'Jayanagar', type: 'origin', sequence: 1 },
      { name: 'Basavanagudi', type: 'stop', sequence: 2 },
      { name: 'Banashankari', type: 'stop', sequence: 3 },
      { name: 'Uttarahalli', type: 'stop', sequence: 4 },
      { name: 'JP Nagar', type: 'destination', sequence: 5 },
    ],
    manualStops: [
      { name: 'JP Nagar', sequence: 1 },
      { name: 'Jayanagar', sequence: 2 },
      { name: 'Uttarahalli', sequence: 3 },
      { name: 'Basavanagudi', sequence: 4 },
      { name: 'Banashankari', sequence: 5 },
    ],
  },
  {
    id: 'OPT-017',
    company: 'Zomato',
    city: 'New Delhi',
    state: 'Delhi',
    driver: 'Manish Tiwari',
    driverInitials: 'MT',
    vehicleId: 'DL-8891',
    origin: 'Vasant Kunj',
    destination: 'Saket',
    stops: 9,
    manualDistance: 49,
    manualFuelCost: 834,
    manualTime: '2h 44m',
    manualTimeMinutes: 164,
    optimizedDistance: 33,
    optimizedFuelCost: 561,
    optimizedTime: '1h 51m',
    optimizedTimeMinutes: 111,
    distanceSaved: 16,
    fuelSaved: 273,
    timeSaved: 53,
    distanceReduction: 33,
    status: 'Completed',
    optimizedAt: '08:40 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 14,
    confidence: 91,
    routeStops: [
      { name: 'Vasant Kunj', type: 'origin', sequence: 1 },
      { name: 'Vasant Vihar', type: 'stop', sequence: 2 },
      { name: 'Munirka', type: 'stop', sequence: 3 },
      { name: 'IIT Delhi', type: 'stop', sequence: 4 },
      { name: 'Saket', type: 'destination', sequence: 5 },
    ],
    manualStops: [
      { name: 'Saket', sequence: 1 },
      { name: 'Vasant Kunj', sequence: 2 },
      { name: 'IIT Delhi', sequence: 3 },
      { name: 'Vasant Vihar', sequence: 4 },
      { name: 'Munirka', sequence: 5 },
    ],
  },
  {
    id: 'OPT-018',
    company: 'Blinkit',
    city: 'New Delhi',
    state: 'Delhi',
    driver: 'Ajay Chauhan',
    driverInitials: 'AC',
    vehicleId: 'DL-1192',
    origin: 'Uttam Nagar',
    destination: 'Janakpuri',
    stops: 5,
    manualDistance: 30,
    manualFuelCost: 511,
    manualTime: '1h 41m',
    manualTimeMinutes: 101,
    optimizedDistance: 21,
    optimizedFuelCost: 357,
    optimizedTime: '1h 11m',
    optimizedTimeMinutes: 71,
    distanceSaved: 9,
    fuelSaved: 154,
    timeSaved: 30,
    distanceReduction: 30,
    status: 'Completed',
    optimizedAt: '08:05 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 10,
    confidence: 85,
    routeStops: [
      { name: 'Uttam Nagar', type: 'origin', sequence: 1 },
      { name: 'Nawada', type: 'stop', sequence: 2 },
      { name: 'Dwarka Mor', type: 'stop', sequence: 3 },
      { name: 'Janakpuri', type: 'destination', sequence: 4 },
    ],
    manualStops: [
      { name: 'Janakpuri', sequence: 1 },
      { name: 'Uttam Nagar', sequence: 2 },
      { name: 'Dwarka Mor', sequence: 3 },
      { name: 'Nawada', sequence: 4 },
    ],
  },
  {
    id: 'OPT-019',
    company: 'Blinkit',
    city: 'Mumbai',
    state: 'Maharashtra',
    driver: 'Nilesh More',
    driverInitials: 'NM',
    vehicleId: 'MH-3341',
    origin: 'Borivali West',
    destination: 'Kandivali East',
    stops: 6,
    manualDistance: 36,
    manualFuelCost: 613,
    manualTime: '2h 01m',
    manualTimeMinutes: 121,
    optimizedDistance: 25,
    optimizedFuelCost: 425,
    optimizedTime: '1h 25m',
    optimizedTimeMinutes: 85,
    distanceSaved: 11,
    fuelSaved: 188,
    timeSaved: 36,
    distanceReduction: 31,
    status: 'Pending',
    optimizedAt: '11:20 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 11,
    confidence: 84,
    routeStops: [
      { name: 'Borivali West', type: 'origin', sequence: 1 },
      { name: 'Eksar Road', type: 'stop', sequence: 2 },
      { name: 'Poisar', type: 'stop', sequence: 3 },
      { name: 'Thakur Village', type: 'stop', sequence: 4 },
      { name: 'Kandivali East', type: 'destination', sequence: 5 },
    ],
    manualStops: [
      { name: 'Kandivali East', sequence: 1 },
      { name: 'Borivali West', sequence: 2 },
      { name: 'Thakur Village', sequence: 3 },
      { name: 'Eksar Road', sequence: 4 },
      { name: 'Poisar', sequence: 5 },
    ],
  },
  {
    id: 'OPT-020',
    company: 'Blinkit',
    city: 'Bengaluru',
    state: 'Karnataka',
    driver: 'Sunil Hegde',
    driverInitials: 'SH',
    vehicleId: 'KA-7789',
    origin: 'Rajajinagar',
    destination: 'Malleshwaram',
    stops: 7,
    manualDistance: 41,
    manualFuelCost: 698,
    manualTime: '2h 18m',
    manualTimeMinutes: 138,
    optimizedDistance: 28,
    optimizedFuelCost: 476,
    optimizedTime: '1h 34m',
    optimizedTimeMinutes: 94,
    distanceSaved: 13,
    fuelSaved: 222,
    timeSaved: 44,
    distanceReduction: 32,
    status: 'Active',
    optimizedAt: '10:05 AM',
    algorithm: 'DBSCAN + TSP',
    variablesUsed: 13,
    confidence: 90,
    routeStops: [
      { name: 'Rajajinagar', type: 'origin', sequence: 1 },
      { name: 'Vijayanagar', type: 'stop', sequence: 2 },
      { name: 'Nagarbhavi', type: 'stop', sequence: 3 },
      { name: 'Yeshwanthpur', type: 'stop', sequence: 4 },
      { name: 'Malleshwaram', type: 'destination', sequence: 5 },
    ],
    manualStops: [
      { name: 'Malleshwaram', sequence: 1 },
      { name: 'Rajajinagar', sequence: 2 },
      { name: 'Yeshwanthpur', sequence: 3 },
      { name: 'Vijayanagar', sequence: 4 },
      { name: 'Nagarbhavi', sequence: 5 },
    ],
  },
];

export const OPTIMIZATION_SUMMARY = {
  totalRoutesOptimized: 247,
  totalFuelSaved: 71530,
  totalTimeSaved: 13585,
  avgDistanceReduction: 35,
  avgOptimizationTime: 8,
  maxStopsSupported: 50,
  algorithmVersion: 'DBSCAN v2.4 + TSP Solver',
  lastOptimizedAt: '2 min ago',
};