// src/pages/admin/AIDelayPrediction/AIDelayData.js

export const ALL_ROUTES = [
  {
    id: 'RT-001',
    route: 'Sector 14 → CP',
    origin: 'Sector 14',
    destination: 'Connaught Place',
    driver: 'Rajan Kumar',
    driverInitials: 'RK',
    vehicleId: 'DL-4521',
    company: 'Amazon',
    city: 'New Delhi',
    state: 'Delhi',
    riskScore: 82,
    riskLevel: 'HIGH',
    predictedDelay: '+24 min',
    delayMinutes: 24,
    cause: 'Traffic jam',
    causes: [
      { factor: 'Live Traffic', weight: 45, impact: 'HIGH' },
      { factor: 'Time of Day', weight: 22, impact: 'MEDIUM' },
      { factor: 'Driver History', weight: 15, impact: 'LOW' },
      { factor: 'Weather', weight: 18, impact: 'MEDIUM' }
    ],
    action: 'Reroute',
    confidence: 94,
    lastUpdated: '90 sec ago',
    eta: '4:45 PM',
    slaDeadline: '5:00 PM',
    slaStatus: 'At Risk',
    distance: '8.2 km',
    alternateRouteAvailable: true,
    alternateTimeSaving: '18 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-002',
    route: 'Noida Sector 62 → Cyber Hub',
    origin: 'Noida Sector 62',
    destination: 'Cyber Hub',
    driver: 'Priya Sharma',
    driverInitials: 'PS',
    vehicleId: 'DL-7892',
    company: 'Flipkart',
    city: 'New Delhi',
    state: 'Delhi',
    riskScore: 68,
    riskLevel: 'MEDIUM',
    predictedDelay: '+14 min',
    delayMinutes: 14,
    cause: 'Weather',
    causes: [
      { factor: 'Weather Forecast', weight: 40, impact: 'HIGH' },
      { factor: 'Live Traffic', weight: 30, impact: 'MEDIUM' },
      { factor: 'Time of Day', weight: 15, impact: 'LOW' },
      { factor: 'Vehicle Health', weight: 15, impact: 'MEDIUM' }
    ],
    action: 'Monitor',
    confidence: 88,
    lastUpdated: '90 sec ago',
    eta: '6:10 PM',
    slaDeadline: '6:30 PM',
    slaStatus: 'At Risk',
    distance: '12.5 km',
    alternateRouteAvailable: true,
    alternateTimeSaving: '9 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-003',
    route: 'Andheri → BKC',
    origin: 'Andheri',
    destination: 'BKC',
    driver: 'Arjun Tiwari',
    driverInitials: 'AT',
    vehicleId: 'MH-1234',
    company: 'Amazon',
    city: 'Mumbai',
    state: 'Maharashtra',
    riskScore: 23,
    riskLevel: 'LOW',
    predictedDelay: 'On Time',
    delayMinutes: 0,
    cause: 'Clear route',
    causes: [
      { factor: 'Live Traffic', weight: 30, impact: 'LOW' },
      { factor: 'Time of Day', weight: 25, impact: 'LOW' },
      { factor: 'Driver History', weight: 20, impact: 'LOW' },
      { factor: 'Road Conditions', weight: 25, impact: 'MEDIUM' }
    ],
    action: 'None',
    confidence: 96,
    lastUpdated: '90 sec ago',
    eta: '3:15 PM',
    slaDeadline: '3:30 PM',
    slaStatus: 'On Track',
    distance: '6.8 km',
    alternateRouteAvailable: false,
    alternateTimeSaving: '0 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-004',
    route: 'Whitefield → MG Road',
    origin: 'Whitefield',
    destination: 'MG Road',
    driver: 'Meena Patel',
    driverInitials: 'MP',
    vehicleId: 'KA-5678',
    company: 'Meesho',
    city: 'Bengaluru',
    state: 'Karnataka',
    riskScore: 71,
    riskLevel: 'MEDIUM',
    predictedDelay: '+18 min',
    delayMinutes: 18,
    cause: 'Road work',
    causes: [
      { factor: 'Road Conditions', weight: 50, impact: 'HIGH' },
      { factor: 'Live Traffic', weight: 30, impact: 'MEDIUM' },
      { factor: 'Time of Day', weight: 12, impact: 'LOW' },
      { factor: 'Driver History', weight: 8, impact: 'LOW' }
    ],
    action: 'Alert',
    confidence: 86,
    lastUpdated: '90 sec ago',
    eta: '5:45 PM',
    slaDeadline: '5:15 PM',
    slaStatus: 'Breached',
    distance: '14.3 km',
    alternateRouteAvailable: true,
    alternateTimeSaving: '12 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-005',
    route: 'T Nagar → Adyar',
    origin: 'T Nagar',
    destination: 'Adyar',
    driver: 'Karan Singh',
    driverInitials: 'KS',
    vehicleId: 'TN-9012',
    company: 'Zomato',
    city: 'Chennai',
    state: 'Tamil Nadu',
    riskScore: 15,
    riskLevel: 'LOW',
    predictedDelay: 'On Time',
    delayMinutes: 0,
    cause: 'Clear route',
    causes: [
      { factor: 'Live Traffic', weight: 35, impact: 'LOW' },
      { factor: 'Time of Day', weight: 25, impact: 'LOW' },
      { factor: 'Area Congestion', weight: 20, impact: 'LOW' },
      { factor: 'Fuel Level', weight: 20, impact: 'LOW' }
    ],
    action: 'None',
    confidence: 97,
    lastUpdated: '90 sec ago',
    eta: '12:40 PM',
    slaDeadline: '1:00 PM',
    slaStatus: 'On Track',
    distance: '5.0 km',
    alternateRouteAvailable: true,
    alternateTimeSaving: '5 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-006',
    route: 'Ludhiana → Jalandhar',
    origin: 'Ludhiana',
    destination: 'Jalandhar',
    driver: 'Harpreet Kaur',
    driverInitials: 'HK',
    vehicleId: 'PB-3456',
    company: 'Blinkit',
    city: 'Ludhiana',
    state: 'Punjab',
    riskScore: 45,
    riskLevel: 'MEDIUM',
    predictedDelay: '+10 min',
    delayMinutes: 10,
    cause: 'Vehicle issue',
    causes: [
      { factor: 'Vehicle Health', weight: 50, impact: 'HIGH' },
      { factor: 'Driver History', weight: 25, impact: 'MEDIUM' },
      { factor: 'Live Traffic', weight: 15, impact: 'LOW' },
      { factor: 'Weather', weight: 10, impact: 'LOW' }
    ],
    action: 'Alert',
    confidence: 83,
    lastUpdated: '90 sec ago',
    eta: '2:20 PM',
    slaDeadline: '2:40 PM',
    slaStatus: 'At Risk',
    distance: '45.0 km',
    alternateRouteAvailable: false,
    alternateTimeSaving: '0 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-007',
    route: 'Dwarka → Gurgaon',
    origin: 'Dwarka',
    destination: 'Gurgaon',
    driver: 'Vikram Joshi',
    driverInitials: 'VJ',
    vehicleId: 'DL-1122',
    company: 'Amazon',
    city: 'New Delhi',
    state: 'Delhi',
    riskScore: 88,
    riskLevel: 'HIGH',
    predictedDelay: '+30 min',
    delayMinutes: 30,
    cause: 'Severe congestion',
    causes: [
      { factor: 'Live Traffic', weight: 55, impact: 'HIGH' },
      { factor: 'Time of Day', weight: 25, impact: 'MEDIUM' },
      { factor: 'Area Congestion', weight: 15, impact: 'HIGH' },
      { factor: 'Weather', weight: 5, impact: 'LOW' }
    ],
    action: 'Reroute',
    confidence: 91,
    lastUpdated: '90 sec ago',
    eta: '7:10 PM',
    slaDeadline: '6:30 PM',
    slaStatus: 'Breached',
    distance: '18.0 km',
    alternateRouteAvailable: true,
    alternateTimeSaving: '22 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-008',
    route: 'Pune Station → Hinjewadi',
    origin: 'Pune Station',
    destination: 'Hinjewadi',
    driver: 'Sneha More',
    driverInitials: 'SM',
    vehicleId: 'MH-9988',
    company: 'Flipkart',
    city: 'Pune',
    state: 'Maharashtra',
    riskScore: 52,
    riskLevel: 'MEDIUM',
    predictedDelay: '+12 min',
    delayMinutes: 12,
    cause: 'Moderate traffic',
    causes: [
      { factor: 'Live Traffic', weight: 40, impact: 'MEDIUM' },
      { factor: 'Time of Day', weight: 30, impact: 'MEDIUM' },
      { factor: 'Package Count', weight: 15, impact: 'LOW' },
      { factor: 'Driver History', weight: 15, impact: 'LOW' }
    ],
    action: 'Monitor',
    confidence: 87,
    lastUpdated: '90 sec ago',
    eta: '11:45 AM',
    slaDeadline: '12:00 PM',
    slaStatus: 'At Risk',
    distance: '15.0 km',
    alternateRouteAvailable: true,
    alternateTimeSaving: '7 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-009',
    route: 'Koramangala → Electronic City',
    origin: 'Koramangala',
    destination: 'Electronic City',
    driver: 'Rohit Reddy',
    driverInitials: 'RR',
    vehicleId: 'KA-2233',
    company: 'Meesho',
    city: 'Bengaluru',
    state: 'Karnataka',
    riskScore: 38,
    riskLevel: 'LOW',
    predictedDelay: 'On Time',
    delayMinutes: 0,
    cause: 'Normal conditions',
    causes: [
      { factor: 'Live Traffic', weight: 30, impact: 'LOW' },
      { factor: 'Road Conditions', weight: 25, impact: 'LOW' },
      { factor: 'Time of Day', weight: 25, impact: 'LOW' },
      { factor: 'Vehicle Health', weight: 20, impact: 'LOW' }
    ],
    action: 'None',
    confidence: 95,
    lastUpdated: '90 sec ago',
    eta: '4:00 PM',
    slaDeadline: '4:20 PM',
    slaStatus: 'On Track',
    distance: '8.0 km',
    alternateRouteAvailable: true,
    alternateTimeSaving: '3 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-010',
    route: 'Velachery → OMR',
    origin: 'Velachery',
    destination: 'OMR',
    driver: 'Deepa Nair',
    driverInitials: 'DN',
    vehicleId: 'TN-5678',
    company: 'Amazon',
    city: 'Chennai',
    state: 'Tamil Nadu',
    riskScore: 64,
    riskLevel: 'MEDIUM',
    predictedDelay: '+15 min',
    delayMinutes: 15,
    cause: 'Tech park rush',
    causes: [
      { factor: 'Time of Day', weight: 45, impact: 'HIGH' },
      { factor: 'Live Traffic', weight: 30, impact: 'MEDIUM' },
      { factor: 'Area Congestion', weight: 15, impact: 'MEDIUM' },
      { factor: 'Weather', weight: 10, impact: 'LOW' }
    ],
    action: 'Monitor',
    confidence: 84,
    lastUpdated: '90 sec ago',
    eta: '6:25 PM',
    slaDeadline: '6:35 PM',
    slaStatus: 'At Risk',
    distance: '11.0 km',
    alternateRouteAvailable: true,
    alternateTimeSaving: '10 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-011',
    route: 'Chandni Chowk → Karol Bagh',
    origin: 'Chandni Chowk',
    destination: 'Karol Bagh',
    driver: 'Amit Verma',
    driverInitials: 'AV',
    vehicleId: 'DL-3344',
    company: 'Blinkit',
    city: 'New Delhi',
    state: 'Delhi',
    riskScore: 79,
    riskLevel: 'HIGH',
    predictedDelay: '+22 min',
    delayMinutes: 22,
    cause: 'Market congestion',
    causes: [
      { factor: 'Area Congestion', weight: 60, impact: 'HIGH' },
      { factor: 'Live Traffic', weight: 25, impact: 'MEDIUM' },
      { factor: 'Time of Day', weight: 10, impact: 'LOW' },
      { factor: 'Driver History', weight: 5, impact: 'LOW' }
    ],
    action: 'Reroute',
    confidence: 89,
    lastUpdated: '90 sec ago',
    eta: '1:55 PM',
    slaDeadline: '2:00 PM',
    slaStatus: 'At Risk',
    distance: '4.5 km',
    alternateRouteAvailable: true,
    alternateTimeSaving: '15 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-012',
    route: 'Nagpur → Wardha',
    origin: 'Nagpur',
    destination: 'Wardha',
    driver: 'Sunil Kamble',
    driverInitials: 'SK',
    vehicleId: 'MH-4455',
    company: 'Zomato',
    city: 'Nagpur',
    state: 'Maharashtra',
    riskScore: 10,
    riskLevel: 'LOW',
    predictedDelay: 'On Time',
    delayMinutes: 0,
    cause: 'Clear highway',
    causes: [
      { factor: 'Road Conditions', weight: 35, impact: 'LOW' },
      { factor: 'Live Traffic', weight: 30, impact: 'LOW' },
      { factor: 'Time of Day', weight: 20, impact: 'LOW' },
      { factor: 'Vehicle Health', weight: 15, impact: 'LOW' }
    ],
    action: 'None',
    confidence: 99,
    lastUpdated: '90 sec ago',
    eta: '10:20 AM',
    slaDeadline: '10:40 AM',
    slaStatus: 'On Track',
    distance: '75.0 km',
    alternateRouteAvailable: false,
    alternateTimeSaving: '0 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-013',
    route: 'HSR Layout → Indiranagar',
    origin: 'HSR Layout',
    destination: 'Indiranagar',
    driver: 'Nisha Gupta',
    driverInitials: 'NG',
    vehicleId: 'KA-7788',
    company: 'Flipkart',
    city: 'Bengaluru',
    state: 'Karnataka',
    riskScore: 41,
    riskLevel: 'MEDIUM',
    predictedDelay: '+9 min',
    delayMinutes: 9,
    cause: 'Rain showers',
    causes: [
      { factor: 'Weather', weight: 60, impact: 'HIGH' },
      { factor: 'Live Traffic', weight: 20, impact: 'MEDIUM' },
      { factor: 'Road Conditions', weight: 10, impact: 'LOW' },
      { factor: 'Driver History', weight: 10, impact: 'LOW' }
    ],
    action: 'Alert',
    confidence: 85,
    lastUpdated: '90 sec ago',
    eta: '5:10 PM',
    slaDeadline: '5:20 PM',
    slaStatus: 'On Track',
    distance: '6.5 km',
    alternateRouteAvailable: true,
    alternateTimeSaving: '6 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-014',
    route: 'Amritsar → Jalandhar',
    origin: 'Amritsar',
    destination: 'Jalandhar',
    driver: 'Gurpreet Singh',
    driverInitials: 'GS',
    vehicleId: 'PB-5566',
    company: 'Meesho',
    city: 'Amritsar',
    state: 'Punjab',
    riskScore: 55,
    riskLevel: 'MEDIUM',
    predictedDelay: '+13 min',
    delayMinutes: 13,
    cause: 'Border check',
    causes: [
      { factor: 'Area Congestion', weight: 50, impact: 'HIGH' },
      { factor: 'Live Traffic', weight: 25, impact: 'MEDIUM' },
      { factor: 'Time of Day', weight: 15, impact: 'LOW' },
      { factor: 'Driver History', weight: 10, impact: 'LOW' }
    ],
    action: 'Monitor',
    confidence: 82,
    lastUpdated: '90 sec ago',
    eta: '3:30 PM',
    slaDeadline: '3:40 PM',
    slaStatus: 'On Track',
    distance: '55.0 km',
    alternateRouteAvailable: true,
    alternateTimeSaving: '20 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-015',
    route: 'Thane → Navi Mumbai',
    origin: 'Thane',
    destination: 'Navi Mumbai',
    driver: 'Pooja Shetty',
    driverInitials: 'PS',
    vehicleId: 'MH-6677',
    company: 'Amazon',
    city: 'Thane',
    state: 'Maharashtra',
    riskScore: 93,
    riskLevel: 'HIGH',
    predictedDelay: '+35 min',
    delayMinutes: 35,
    cause: 'Accident on route',
    causes: [
      { factor: 'Live Traffic', weight: 70, impact: 'HIGH' },
      { factor: 'Time of Day', weight: 15, impact: 'MEDIUM' },
      { factor: 'Area Congestion', weight: 10, impact: 'HIGH' },
      { factor: 'Weather', weight: 5, impact: 'LOW' }
    ],
    action: 'Reroute',
    confidence: 90,
    lastUpdated: '90 sec ago',
    eta: '8:05 PM',
    slaDeadline: '7:30 PM',
    slaStatus: 'Breached',
    distance: '22.0 km',
    alternateRouteAvailable: true,
    alternateTimeSaving: '25 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-016',
    route: 'Shivajinagar → Banashankari',
    origin: 'Shivajinagar',
    destination: 'Banashankari',
    driver: 'Rajesh Gowda',
    driverInitials: 'RG',
    vehicleId: 'KA-9900',
    company: 'Blinkit',
    city: 'Bengaluru',
    state: 'Karnataka',
    riskScore: 31,
    riskLevel: 'LOW',
    predictedDelay: 'On Time',
    delayMinutes: 0,
    cause: 'Smooth traffic',
    causes: [
      { factor: 'Live Traffic', weight: 30, impact: 'LOW' },
      { factor: 'Time of Day', weight: 25, impact: 'LOW' },
      { factor: 'Driver History', weight: 25, impact: 'LOW' },
      { factor: 'Vehicle Health', weight: 20, impact: 'LOW' }
    ],
    action: 'None',
    confidence: 94,
    lastUpdated: '90 sec ago',
    eta: '12:10 PM',
    slaDeadline: '12:30 PM',
    slaStatus: 'On Track',
    distance: '5.5 km',
    alternateRouteAvailable: false,
    alternateTimeSaving: '0 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-017',
    route: 'Chromepet → Guindy',
    origin: 'Chromepet',
    destination: 'Guindy',
    driver: 'Mohan Raj',
    driverInitials: 'MR',
    vehicleId: 'TN-1234',
    company: 'Zomato',
    city: 'Chennai',
    state: 'Tamil Nadu',
    riskScore: 60,
    riskLevel: 'MEDIUM',
    predictedDelay: '+11 min',
    delayMinutes: 11,
    cause: 'College area rush',
    causes: [
      { factor: 'Time of Day', weight: 45, impact: 'HIGH' },
      { factor: 'Area Congestion', weight: 30, impact: 'MEDIUM' },
      { factor: 'Live Traffic', weight: 15, impact: 'LOW' },
      { factor: 'Weather', weight: 10, impact: 'LOW' }
    ],
    action: 'Monitor',
    confidence: 83,
    lastUpdated: '90 sec ago',
    eta: '9:50 AM',
    slaDeadline: '10:00 AM',
    slaStatus: 'On Track',
    distance: '7.5 km',
    alternateRouteAvailable: true,
    alternateTimeSaving: '8 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-018',
    route: 'Rohini → Pitampura',
    origin: 'Rohini',
    destination: 'Pitampura',
    driver: 'Sakshi Jain',
    driverInitials: 'SJ',
    vehicleId: 'DL-5566',
    company: 'Flipkart',
    city: 'New Delhi',
    state: 'Delhi',
    riskScore: 19,
    riskLevel: 'LOW',
    predictedDelay: 'On Time',
    delayMinutes: 0,
    cause: 'Clear route',
    causes: [
      { factor: 'Live Traffic', weight: 30, impact: 'LOW' },
      { factor: 'Time of Day', weight: 25, impact: 'LOW' },
      { factor: 'Driver History', weight: 25, impact: 'LOW' },
      { factor: 'Vehicle Health', weight: 20, impact: 'LOW' }
    ],
    action: 'None',
    confidence: 96,
    lastUpdated: '90 sec ago',
    eta: '3:55 PM',
    slaDeadline: '4:15 PM',
    slaStatus: 'On Track',
    distance: '3.2 km',
    alternateRouteAvailable: false,
    alternateTimeSaving: '0 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-019',
    route: 'Dadar → Worli',
    origin: 'Dadar',
    destination: 'Worli',
    driver: 'Vijay Patil',
    driverInitials: 'VP',
    vehicleId: 'MH-3344',
    company: 'Meesho',
    city: 'Mumbai',
    state: 'Maharashtra',
    riskScore: 74,
    riskLevel: 'MEDIUM',
    predictedDelay: '+20 min',
    delayMinutes: 20,
    cause: 'Event traffic',
    causes: [
      { factor: 'Area Congestion', weight: 55, impact: 'HIGH' },
      { factor: 'Live Traffic', weight: 25, impact: 'MEDIUM' },
      { factor: 'Time of Day', weight: 15, impact: 'LOW' },
      { factor: 'Weather', weight: 5, impact: 'LOW' }
    ],
    action: 'Alert',
    confidence: 81,
    lastUpdated: '90 sec ago',
    eta: '7:40 PM',
    slaDeadline: '7:25 PM',
    slaStatus: 'Breached',
    distance: '4.0 km',
    alternateRouteAvailable: true,
    alternateTimeSaving: '14 min',
    modelVersion: 'v2.4.1'
  },
  {
    id: 'RT-020',
    route: 'Lajpat Nagar → South Ex',
    origin: 'Lajpat Nagar',
    destination: 'South Extension',
    driver: 'Ritu Aggarwal',
    driverInitials: 'RA',
    vehicleId: 'DL-8888',
    company: 'Zomato',
    city: 'New Delhi',
    state: 'Delhi',
    riskScore: 27,
    riskLevel: 'LOW',
    predictedDelay: 'On Time',
    delayMinutes: 0,
    cause: 'Normal flow',
    causes: [
      { factor: 'Live Traffic', weight: 35, impact: 'LOW' },
      { factor: 'Time of Day', weight: 25, impact: 'LOW' },
      { factor: 'Driver History', weight: 20, impact: 'LOW' },
      { factor: 'Vehicle Health', weight: 20, impact: 'LOW' }
    ],
    action: 'None',
    confidence: 97,
    lastUpdated: '90 sec ago',
    eta: '2:35 PM',
    slaDeadline: '2:55 PM',
    slaStatus: 'On Track',
    distance: '2.8 km',
    alternateRouteAvailable: false,
    alternateTimeSaving: '0 min',
    modelVersion: 'v2.4.1'
  }
];

export const PREDICTION_METRICS = {
  accuracy: 82,
  accuracyTrend: '+3.2% this week',
  avgDeviation: 4,
  deviationTrend: 'Improved 31% in 30 days',
  routesAnalyzed: 247,
  lastRun: '90 sec ago',
  modelVersion: 'v2.4.1',
  totalVariables: 14
};

export const HOURLY_ACCURACY = [
  { hour: '8AM', accuracy: 78, predictions: 18 },
  { hour: '9AM', accuracy: 82, predictions: 24 },
  { hour: '10AM', accuracy: 85, predictions: 21 },
  { hour: '11AM', accuracy: 87, predictions: 19 },
  { hour: '12PM', accuracy: 88, predictions: 22 },
  { hour: '1PM', accuracy: 87, predictions: 20 },
  { hour: '2PM', accuracy: 89, predictions: 25 },
  { hour: '3PM', accuracy: 86, predictions: 23 },
  { hour: '4PM', accuracy: 84, predictions: 21 },
  { hour: '5PM', accuracy: 81, predictions: 26 },
  { hour: '6PM', accuracy: 79, predictions: 24 },
  { hour: '7PM', accuracy: 76, predictions: 19 },
  { hour: '8PM', accuracy: 74, predictions: 16 }
];

export const VARIABLES = [
  { name: 'Live Traffic', icon: '🚦', weight: 28, category: 'Real-time' },
  { name: 'Weather Forecast', icon: '🌧', weight: 15, category: 'Environmental' },
  { name: 'Driver History', icon: '🚗', weight: 12, category: 'Historical' },
  { name: 'Package Count', icon: '📦', weight: 6, category: 'Operational' },
  { name: 'Road Conditions', icon: '🛣', weight: 10, category: 'Real-time' },
  { name: 'Time of Day', icon: '⏰', weight: 8, category: 'Real-time' },
  { name: 'Area Congestion', icon: '🏙', weight: 7, category: 'Real-time' },
  { name: 'Fuel Level', icon: '⛽', weight: 3, category: 'Operational' },
  { name: 'Vehicle Health', icon: '🔧', weight: 4, category: 'Operational' },
  { name: 'Current Speed', icon: '📍', weight: 5, category: 'Real-time' },
  { name: 'Day of Week', icon: '📅', weight: 2, category: 'Historical' },
  { name: 'Warehouse Load', icon: '🏭', weight: 3, category: 'Operational' },
  { name: 'Reroute History', icon: '🔄', weight: 2, category: 'Historical' },
  { name: 'SLA Deadline', icon: '⚡', weight: 5, category: 'Operational' }
];